sudo: false
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- echo "skip test"
deploy:
  skip_cleanup: true
  provider: pypi
  user: swind
  password:
    secure: GjGXSJk5e52is++wzUv0/SmWtEAIXv7WcFq+p+SzFx4aOn+gnT6yp0zY/9C4qNFJk8p2TbCawbFicK7WUCqd0QoUTiG495SwlIEf5FHa2L0qWFVU2KLNLXB/FD2GosqnpsL/FIOwIqFzZ/PjeEpnDx45d7yZhXR571bdgMxzah89gQZgsHS2eBrjwKMNjTRpNP+hlGbiMRLyYh2Ay0UJG4wGL92FoOooboB6z473ZdyIKq5Hsah4+WhvQWV/oPwqLS18us4tF0zd4YO4cG8T+cgdIBF/+xgpQTSQEaWWAzi/f1PK99KtNJuy2NV+TFL03CMRBSfr0UDMoU4neSKVNXC51F9uNQCTQN2NGOtK2SJlPvQqbsnaN2IL83DA3r4RxHtHoY0U7AsTt448FDwrLrfMEDtOrocJ2DdxI/oBpkTB3/2eMZYzcUfRruxNsq05N4V8uhRyH4/tQnMU8+LEWdGfsgpZkb3ag3sZucdojFBwacBOgS/aOms/t3cQRT4wHLAYd4nYMz5ZzGKZOxv18+C95YEXl4L3vLB1ur1C/xPpfAMYJssN7MAZah+sWi6IOZGWa4DiITEJKf8NaIcM5WyUImxT+/TGvPSdLoUb5WgOqnBaiiK+4P8n8RzvUYfMvLp6G9mV0p7yctgUwUSr7dsuwyObn7UlNuuxAYGpvsM=
  on:
    tags: true
